packages:
- .
resolver:
  compiler: ghc-9.2.4
ghc-options:
  $everything: -haddock
extra-deps:
  - heap-1.0.4@sha256:ad0e192efbff268e85042068c308c69fa6c787c3cd6ab96c34f89e5bfee01cf9,1556
nix:
  packages:
  - zlib
  enable: true
